### ISSUE TITLE
Add option to view template configuration

### ISSUE THREAD

**Issue by mantunovic** [RobinUS2/indispenso#23]
As on templates list there are only options for execute and delete, for new users would be useful to have view option to become familiar with something that would like to execute

**Comment by RobinUS2** [comment]
I will start working on this, thanks for the feedback!

**Comment by mantunovic** [comment]
Would be good to have edit option too. 

Thanks,
Mladen

**Comment by RobinUS2** [comment]
Agree. For now I have added more info to the first screen of "execute" which you could see as view as well. Will create a new issue for editing.
